# Generated by Django 5.2.6 on 2025-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='datahora',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='fim',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='inicio',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
