# Generated by Django 5.2.6 on 2025-10-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0002_remove_reuniao_datahora_reuniao_fim_reuniao_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='cliente',
        ),
    ]
