# Generated by Django 5.2.7 on 2026-03-16 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_domain'),
        ('reunioes', '0004_reuniao_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
