# Generated by Django 5.2.7 on 2026-03-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='domain',
            field=models.CharField(default='localhost:8000', max_length=200),
        ),
    ]
