# Generated by Django 5.2.2 on 2025-06-05 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist'),
            preserve_default=False,
        ),
    ]
