# Generated by Django 5.2.3 on 2025-07-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklistitem_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
    ]
