# Generated by Django 5.2.3 on 2025-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
