# Generated by Django 5.2.2 on 2025-06-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('inicio', models.DateTimeField(default=None)),
                ('fim', models.DateTimeField(default=None)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa')),
            ],
        ),
    ]
