# Generated by Django 5.2.2 on 2025-06-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefatempo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
