# Generated by Django 5.2.2 on 2025-06-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklistitem_checklist'),
        ('tarefas', '0004_alter_tarefatempo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_entrega',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABE', 'Aberta'), ('AND', 'Andamento'), ('CON', 'Concluida')], default='ABE', max_length=3),
        ),
        migrations.CreateModel(
            name='TarefaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklistitem')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa')),
            ],
        ),
    ]
