# Generated by Django 5.2.2 on 2025-06-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_tarefa_data_entrega_tarefa_status_tarefachecklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_entrega',
            field=models.DateField(),
        ),
    ]
