# Generated by Django 5.2.2 on 2025-06-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_alter_tarefa_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefatempo',
            name='fim',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='tarefatempo',
            name='inicio',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
