# Generated by Django 5.2.2 on 2025-06-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefatempo_fim_alter_tarefatempo_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefatempo',
            name='fim',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
