# Generated by Django 5.2.2 on 2025-06-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_alter_tarefatempo_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefatempo',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempos', to='tarefas.tarefa'),
        ),
    ]
