# Generated by Django 5.2.3 on 2025-06-28 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_pago_projeto_status_projeto_valor_and_more'),
        ('tarefas', '0009_alter_tarefatempo_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.projeto'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABE', 'Aberta'), ('AND', 'Andamento'), ('BLK', 'Bloqueada'), ('CON', 'Concluida')], default='ABE', max_length=3),
        ),
    ]
