# Generated by Django 5.2.3 on 2025-07-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_alter_tarefa_projeto_alter_tarefa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefachecklist',
            name='checklist',
        ),
        migrations.AddField(
            model_name='tarefachecklist',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefachecklist',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefachecklist',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='tarefas.tarefa'),
        ),
        migrations.DeleteModel(
            name='TarefaChecklistItem',
        ),
    ]
