# Generated by Django 5.2.3 on 2025-07-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0011_remove_tarefachecklist_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefatempo',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
