# Generated by Django 5.2.3 on 2025-07-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0012_tarefatempo_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['data_entrega']},
        ),
    ]
