# Generated by Django 5.2.5 on 2025-08-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0013_alter_tarefa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefachecklist',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='tarefas.tarefa'),
        ),
    ]
