# Generated by Django 5.2.6 on 2025-10-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0014_alter_tarefachecklist_tarefa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefatempo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tempos', to=settings.AUTH_USER_MODEL),
        ),
    ]
