# Generated by Django 5.2.7 on 2026-03-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_domain'),
        ('tarefas', '0015_tarefa_user_tarefatempo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='empresas.empresa'),
        ),
    ]
