# Generated by Django 5.2.7 on 2026-03-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0017_alter_tarefa_empresa'),
        ('usuarios', '0003_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tarefas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='tarefatempo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tempos', to='usuarios.usuario'),
        ),
    ]
