# Generated by Django 5.2.7 on 2026-03-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0018_tarefa_usuario_tarefatempo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tarefatempo',
            name='user',
        ),
    ]
