# Generated by Django 5.2.3 on 2025-06-28 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_observacoes_cliente_telefone'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='pago',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('ORC', 'Orçado'), ('CTD', 'Contratado'), ('AND', 'Andamento'), ('CON', 'Concluido')], default='ORC', max_length=3),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='clientes.cliente'),
        ),
    ]
