# Generated by Django 5.2.3 on 2025-07-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_pago_projeto_status_projeto_valor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['pago', 'nome']},
        ),
    ]
