# Generated by Django 5.2.6 on 2025-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['pago', 'nome'], 'permissions': [('can_view_payment_info', 'Can view payment information')]},
        ),
    ]
