# Generated by Django 5.2.6 on 2025-09-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_projeto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('ORC', 'Orçado'), ('CTD', 'Contratado'), ('AND', 'Andamento'), ('CON', 'Concluido'), ('BLO', 'Bloqueado')], default='ORC', max_length=3),
        ),
    ]
