# Generated by Django 5.2.6 on 2025-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_projeto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='pagamento',
            field=models.CharField(choices=[('ABE', 'Aberto'), ('CON', 'Concluido'), ('PAR', 'Parcelado'), ('ATR', 'Atrasado'), ('PER', 'Perdido')], default='ABE', max_length=3),
        ),
    ]
