# Generated by Django 5.2.7 on 2026-03-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_domain'),
        ('projetos', '0006_projeto_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='empresas.empresa'),
        ),
    ]
