# Generated by Django 6.0.2 on 2026-03-19 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_projeto_senha_acesso_projeto_senha_expira_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='token_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
