# Generated by Django 5.2.7 on 2026-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_alter_projeto_token_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='progresso',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
